### PR TITLE
removed src folder in asset bundle path

### PR DESCRIPTION
**Pull request by schmunk42**
I needed to change this path, when using i.e. `Box::$collapsed`.
Could you double check this?

Using latest composer, Yii and fxp/asset-plugin.

### CODE REVIEW

**Comment by schmunk42** [comment]
Related #2 :)

Strange thing about the asset path?!

**Comment by Insolita** [comment]
> Strange thing about the asset path?!

It's mystic, i've yii 2.0.8, fresh composer, project started ~month ago 

```
#composer global show|grep fxp
fxp/composer-asset-plugin          v1.1.4  NPM/Bower Dependency Manager for Composer
#composer --version
Composer version 1.1.1 2016-05-17 12:25:44
```

and  bower jquery with **src** dir


> - jQuery Cookie Plugin v1.4.1

when install package jquery-cookie with original bower (bower install jquery-cookie) - folder src not present, but when install it with this extension as dependency folder src always present , i try remove and reinstall it now, i have src folder; 
This package has over 2000 installations from packagist, and only few reports about incorrect asset folder
What about your environment? os? have you installed nodejs/npm/bower?

**Comment by schmunk42** [comment]
I think it's related to the `stability` setting in `composer.json`.

When I install your extension in an application with `stability: "dev"` I get **dev-master** from https://github.com/carhartl/jquery-cookie (with `src/`)

But with `stable` I get this version
https://github.com/carhartl/jquery-cookie/tree/v1.4.1 (without `src/`)

Both double checked with `composer.lock`.

I'll push an update for `composer.json` which should always get you `1.4.1` and up, not updating to `1.5`, since this would be bc-breaking.

**Comment by Insolita** [comment]
ok, thanks

**Pull request merged**
